
cat _system.sql > todo.sql
cat modules.sql >> todo.sql
cat frontpage.sql >> todo.sql
cat pages.sql >> todo.sql
cat regions.sql >> todo.sql
cat widgets.sql >> todo.sql
cat privileges.sql >> todo.sql
cat menus.sql >> todo.sql
cat toolbar.sql >> todo.sql
cat roles.sql >> todo.sql
cat login.sql >> todo.sql
cat users.sql >> todo.sql
cat profile.sql >> todo.sql
cat settings.sql >> todo.sql
cat friends.sql >> todo.sql
cat gestions.sql >> todo.sql
cat subjects.sql >> todo.sql
cat areas.sql >> todo.sql
cat groups.sql >> todo.sql
cat teams.sql >> todo.sql
cat communities.sql >> todo.sql
cat groupsets.sql >> todo.sql
cat resources.sql >> todo.sql
cat notes.sql >> todo.sql
cat files.sql >> todo.sql
cat events.sql >> todo.sql
cat evaluations.sql >> todo.sql
cat califications.sql >> todo.sql
cat comments.sql >> todo.sql
cat ratings.sql >> todo.sql
cat valorations.sql >> todo.sql
cat _extra.sql >> todo.sql

